export const REQUEST_BEGIN = '@@OPN/account/REQUEST_BEGIN';
export const REQUEST_END = '@@OPN/account/REQUEST_END';

export const GET_ACCOUNT_REQUEST = '@@OPN/account/GET_ACCOUNT_REQUEST';
export const GET_ACCOUNT_SUCCESS = '@@OPN/account/GET_ACCOUNT_SUCCESS';
export const GET_ACCOUNT_FAILURE = '@@OPN/account/GET_ACCOUNT_FAILURE';

export const UPDATE_ACCOUNT_REQUEST = '@@OPN/account/UPDATE_ACCOUNT_REQUEST';
export const UPDATE_ACCOUNT_SUCCESS = '@@OPN/account/UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_FAILURE = '@@OPN/account/UPDATE_ACCOUNT_FAILURE';

export const UPDATE_PASSWORD_REQUEST = '@@OPN/account/UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = '@@OPN/account/UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = '@@OPN/account/UPDATE_PASSWORD_FAILURE';

// reset password actions ---
export const SHOW_RESET_FORGOTTEN_PASSWORD_MODAL = '@@OPN/account/SHOW_RESET_FORGOTTEN_PASSWORD_MODAL';
export const HIDE_RESET_FORGOTTEN_PASSWORD_MODAL = '@@OPN/account/HIDE_RESET_FORGOTTEN_PASSWORD_MODAL';

export const RESET_FORGOTTEN_PASSWORD_REQUEST = '@@OPN/account/RESET_FORGOTTEN_PASSWORD_REQUEST';
export const RESET_FORGOTTEN_PASSWORD_SUCCESS = '@@OPN/account/RESET_FORGOTTEN_PASSWORD_SUCCESS';
export const RESET_FORGOTTEN_PASSWORD_FAILURE = '@@OPN/account/RESET_FORGOTTEN_PASSWORD_FAILURE';

export const SENT_RESET_FORGOTTEN_PASSWORD_REQUEST_TO_EMAIL = '@@OPN/account/SENT_RESET_FORGOTTEN_PASSWORD_REQUEST_TO_EMAIL';

export const CONFIRM_RESET_PASSWORD_REQUEST = '@@OPN/account/CONFIRM_RESET_PASSWORD_REQUEST';
export const CONFIRM_RESET_PASSWORD_SUCCESS = '@@OPN/account/CONFIRM_RESET_PASSWORD_SUCCESS';
export const CONFIRM_RESET_PASSWORD_FAILURE = '@@OPN/account/CONFIRM_RESET_PASSWORD_FAILURE';

export const RESET_FORGOTTEN_PASSWORD_CONFIRMED = '@@OPN/account/RESET_FORGOTTEN_PASSWORD_CONFIRMED';

export const DELETE_AVATAR_SUCCESS = '@@OPN/account/DELETE_ACCOUNT_AVATAR_SUCCESS';
export const CROP_AVATAR_SUCCESS = '@@OPN/account/CROP_AVATAR_SUCCESS';
export const SUCCESS_SAVE_USER_AVATAR = '@@OPN/account/SUCCESS_SAVE_USER_AVATAR';
export const SUCCESS_CROP_USER_AVATAR = '@@OPN/account/SUCCESS_CROP_USER_AVATAR';
export const SUCCESS_CROP_PROFILE_AVATAR = '@@OPN/account/SUCCESS_CROP_PROFILE_AVATAR';

export const SHOW_LOGIN_MODAL = '@@OPN/account/SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = '@@OPN/account/HIDE_LOGIN_MODAL';

export const SHOW_REGISTRATION_MODAL = '@@OPN/account/SHOW_REGISTRATION_MODAL';
export const HIDE_REGISTRATION_MODAL = '@@OPN/account/HIDE_REGISTRATION_MODAL';

export const SUCCESS_GET_USER_MEDIA = '@@OPN/account/SUCCESS_GET_USER_MEDIA';

export const SUCCESS_USER_TRIBUTE_PUBLIC = '@@OPN/account/SUCCESS_USER_TRIBUTE_PUBLIC';
export const SUCCESS_USER_TRIBUTE_PRIVATE = '@@OPN/account/SUCCESS_USER_TRIBUTE_PRIVATE';

// user stripe account
export const SUCCESS_GET_STRIPE_ACCOUNT = '@@OPN/account/SUCCESS_GET_STRIPE_ACCOUNT';
export const SUCCESS_ADD_STRIPE_ACCOUNT = '@@OPN/account/SUCCESS_ADD_STRIPE_ACCOUNT';
export const SUCCESS_DELETE_STRIPE_ACCOUNT = '@@OPN/account/SUCCESS_DELETE_STRIPE_ACCOUNT';